### PR TITLE
Update disk selection options and EFI mount path.

### PR DESCRIPTION
**Pull request by mreckhof**
I re-wrote the disk selection and mount pieces to be more flexible and less likely to cause issues to resolve Issue: [Patcher can over-write wrong EFI #20.](https://github.com/dortania/Opencore-Legacy-Patcher/issues/20)

1. The disk selection process filters out any logical partitions and only shows physical partitions.
2. The name of the physical disk is shown
3. The disk selection requires you to specify the proper slice and doesn't assume slice 1.
4. A "likely candidate" is marked (partition type EFI). I intentionally avoided using the word 'recommended'.
5. The mount point changes to /Volumes/OCLP-EFI to avoid anything already mounted as /Volumes/EFI

I tested local install with MacBookPro10,1 and to USB stick on separate system.

### CODE REVIEW

**Comment by MikeBeaton** [comment]
Hi - I'm not on the project, just a user, but if you want to allow the user to select a slice (e.g. `disk0s8`) - which would be helpful, thanks! - then I think you should still list all the slices (logical volumes) prior to offering the choice. E.g. I want to install onto `/Volumes/TEST`, which is my `disk0s8`, but I still need all the logical volumes with their info to be shown in the list (as they used to be) to help me be sure I'm choosing the right one.

**Comment by mreckhof** [comment]
Please do me a favor and run 'diskutil list physical' and see if your slice shows up.  If it does, it'll allow exactly what you're asking.  What it's primarily filtering out are APFS Volumes and Snapshots.

**Comment by mreckhof** [comment]
Here's an example of what it does with various disk types and partition types.

```
Loading diskutil...(This may take some time)

/dev/disk0: WDBRPG0010BNC-WRSN
                TYPE                NAME      SIZE   IDENTIFIER
                 EFI                 EFI  209.7 MB      disk0s1 (*)
          Apple_APFS                      935.5 GB      disk0s2
           Apple_HFS           Test HFS+   32.1 GB      disk0s3
Microsoft Basic Data          TEST_FAT32   32.2 GB      disk0s4

/dev/disk1: WDS200T3X0C-00SJG0
                TYPE                NAME      SIZE   IDENTIFIER
                 EFI                 EFI  209.7 MB      disk1s1 (*)
          Apple_APFS                        2.0 TB      disk1s2

/dev/disk4: USB 3.0 FD
                TYPE                NAME      SIZE   IDENTIFIER
                 EFI                 EFI  209.7 MB      disk4s1 (*)
Microsoft Basic Data            Untitled   34.0 GB      disk4s2

(*) Likely Candidate

Please select the disk IDENTIFIER you want to install OpenCore to (ie. disk1s1): 
```

**Comment by MikeBeaton** [comment]
> Please do me a favor and run 'diskutil list physical' and see if your slice shows up. If it does, it'll allow exactly what you're asking. What it's primarily filtering out are APFS Volumes and Snapshots.

Okay, the required slice does indeed show up! I misunderstood your description and didn't realise how much would show on my machine.

Okay - I like it, and I agree that it does just what I need - and seems to me, too, to be a worthwhile improvement.

+1 from this user for this PR. :)

Thanks!

```
$ diskutil list physical
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *480.1 GB   disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk1⁩         220.0 GB   disk0s2
   3:                  Apple_HFS ⁨Install media⁩           21.3 GB    disk0s3
   4:           Linux Filesystem ⁨⁩                        107.4 GB   disk0s4
   5:       Microsoft Basic Data ⁨Windows 10⁩              130.9 GB   disk0s5
   6:       Microsoft Basic Data ⁨UBUNBOOT⁩                19.9 MB    disk0s6
   7:       Microsoft Basic Data ⁨WINBOOT⁩                 49.3 MB    disk0s7
   8:       Microsoft Basic Data ⁨TEST⁩                    19.9 MB    disk0s8
   9:       Microsoft Basic Data ⁨BOOTHELP⁩                19.9 MB    disk0s9
  10:       Microsoft Basic Data ⁨TO_RECOVERY⁩             19.9 MB    disk0s10
  11:       Microsoft Basic Data ⁨OPENCORE⁩                19.9 MB    disk0s11
```

**Comment by dhinakg** [comment]
Hi, I implemented this in https://github.com/dortania/Opencore-Legacy-Patcher/pull/13/commits/8917368988a5d06ebf122bd8683769c016f9f1d3. Thanks for the PR!

**Pull request closed without merging**
