### PR TITLE
Verbose option

### PR DESCRIPTION
**Pull request by mreckhof**
Adding toggle for verbose booting.

### CODE REVIEW

**Comment by Bmju** [comment]
Just thought worth mentioning that afaik (and actually, having just tested, it works) it is already possible to toggle this with CMD+V before selecting boot option in the OC boot picker (if `Misc/Boot/PollAppleHotkeys` is `true`). Probably that's already evident/well-known and taken into account in deciding the need for this, but just in case not.

**Comment by mreckhof** [comment]
The point of this PR is to be able to set the default.  Right now, the default is verbose.

**Comment by Bmju** [comment]
Ah, apologies - I should be complaining (if anything) about the original decision to make it the default, not about your decision to make it optional. Understood! Thanks.

**Comment by mreckhof** [comment]
I think the default makes sense from a pure support perspective.  Most the folks using these tools don't really know what they do, and if it weren't verbose and going to open canopy by default, people will just think they were bricked and it'd be difficult to help.  Should probably be a whole advanced menu with this option and another to disable the picker by default.

**Comment by mreckhof** [comment]
Note to project maintainers:  I likely screwed up the PR due to my inexperience with git.  So you will likely want to check this against the previous PR (set_smbios inside build_efi) to make sure they both applied right if you accept both.  Apologies.  I'll get this figured out at some point.

**Pull request closed without merging**
