### PR TITLE
Add AppleALC support

### PR DESCRIPTION
**Pull request by khronokernel**
Currently this PR is solely for testing and unlikely to function

### CODE REVIEW

**Comment by NOTNlCE** [comment]
Injecting AppleALC via OpenCore on my iMac12,2, I have "Headphone Port" as an Output device, which does in fact work. I can get you a dump, as requested in PR #75 and will attach.

**Comment by Ausdauersportler** [comment]
Using the same config as NOTNICE I got this on my iMac11,3 right now...(layout-if 24)

internal speakers are not working
external microphone using the stereo chinch on iPhone head set work !!
external speaker on iPhone head set do not work

[Audio.2021.03.05-19.40.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6092730/Audio.2021.03.05-19.40.zip)

**Comment by Jonathan-50** [comment]
MP3,1. With voodoo I had a number of devices showing up but none worked. With ALC (id=13) I have no devices at all.

[Audio.2021.03.08-21.36Voodoo.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6106249/Audio.2021.03.08-21.36Voodoo.zip)

[Audio.2021.03.09-08.10ALCid13.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6106251/Audio.2021.03.09-08.10ALCid13.zip)

**Comment by internetzel** [comment]
My core i5 late 2009 iMac 11,1 gave different results than the 11,3 and the 12,1 :
I used a layout-id of 81 in the DeviceProperties and got two inputs and one output listed:

external microphone (working) - this one is listed as "line-in" with the original driver
optical input - shouldn't that only be listed when a device is plugged in?
internal speakers (no sound output, not even to the headphone output)

external speakers aren't even listed when I connect headphones.

**Pull request closed without merging**
