### PR TITLE
Add TeraScale 2 patches

### PR DESCRIPTION
**Pull request by khronokernel**
Currently experimental, only iMacs and Skylake Hackintosh tested. 

SSE4,2 required, MouSSE is currently [non-functional in Big Sur](https://forums.macrumors.com/threads/mp3-1-others-sse-4-2-emulation-to-enable-amd-metal-driver.2206682/post-29963384)

### CODE REVIEW

**Comment by sharad-paghadal** [comment]
@khronokernel THANK YOU for this! I tried it on Macmini5,2.

Previously I couldn't login after applying patch and loop me into login screen, but now It's working.
Now only 1 issue - screen is flickering continuously on every screen update. e.g even for moving mouse screen is flickering.

**Comment by khronokernel** [comment]
> Now only 1 issue - screen is flickering continuously on every screen update. e.g even for moving mouse screen is flickering.
Install ResXTREME or SwitchResX and force million colors instead of billion. Known issue currently, proper fix will be implemented in the future

**Comment by sharad-paghadal** [comment]
@khronokernel Thank you! that worked!!!!

**Comment by sharad-paghadal** [comment]
@khronokernel Network Screen sharing doesn't load screen. Known issue?

**Comment by khronokernel** [comment]
> Network Screen sharing doesn't load screen. Known issue?

Correct, VNC is currently unsupported. Proper fixes are currently being researched

**Comment by khronokernel** [comment]
Patches implemented into our SysPatch refactor:
https://github.com/dortania/OpenCore-Legacy-Patcher/pull/282

**Pull request closed without merging**
