### PR TITLE
Add more Tesla, Fermi, and Kepler Device IDs

### PR DESCRIPTION
**Pull request by flagersgit**
PCI ID for GTX 650 Ti BOOST (uses GK106 core) is missing from NVIDIA `kepler_ids` PCI ID array.

### CODE REVIEW

**Comment by flagersgit** [comment]
There seem to be yet more missing device ids, specifically these:
New Tesla Device IDs:
`['0190', '0193', '0191', '0194', '019e', '019d', '040f', '040a', '040e', '040d', '040c', '040b', '042c', '042f', '042d', '042e', '042a', '042b', '061a', '061d', '061c', '061e', '061f', '060c', '0624', '062e', '062f', '063a', '062a', '062b', '062c', '065b', '064c', '065c', '064a', '06e4', '06e2', '06e0', '06e1', '06ed', '06e6', '06fd', '06f8', '06fa', '06f9', '06e8', '06e5', '06e9', '06ef', '06ec', '06f1', '06ea', '06eb', '05e2', '05ea', '05e1', '05eb', '05e6', '05e3', '05e0', '05ff', '05fe', '05fd', '0ca5', '0ca3', '0ca2', '0ca0', '0ca4', '0cbc', '0caf', '0ca9', '0cb1', '0a23', '0a22', '0a27', '0a20', '0a3c', '0a28', '0a2a', '0a34', '0a2d', '0a35', '0a29', '0a2b', '0a2c', '0a65', '0a63', '0a66', '0a67', '10c5', '10c3', '0a60', '0a64', '10d8', '0a78', '0a7c', '0a70', '0a72', '0a75', '0a7a', '0a68', '0a69', '0a74', '0a76', '0a6f', '0a6c']`
New Fermi Device IDs:
`['06c4', '06cd', '06c0', '06dd', '06d9', '06d8', '06d1', '06de', '109a', '06ca', '0e23', '0e22', '0e3a', '0e3b', '0dc0', '0dc6', '0dc4', '0dd8', '0dda', '0dd2', '0dd6', '0dcd', '0dce', '0dd1', '0de2', '0de1', '0de0', '0de4', '0de5', '0f01', '0f00', '0f02', '0df8', '0dfc', '0dfa', '0dea', '0dee', '0df1', '0df0', '0df2', '0ded', '0df7', '0dec', '0df5', '0df4', '0df6', '0deb', '0de8', '0de9', '0de3', '0def', '1096', '124d', '104a', '104b', '104c', '107d', '107c', '105a', '105b']`
New Kepler Device IDs:
`['0FC8', '0FCD', '0FDF', '0FE1', '0FE3', '0FE4', '0FEA', '0FEE', '0FF2', '0FF3', '1001', '1007', '100A', '100C', '1023', '1024', '102D', '103C', '1184', '1187', '118E', '118F', '119D', '11B4', '1281', '1286', '1287', '1288', '1289', '128B', '1296', '1298', '1299', '129A']`

Will amend last commit and add the rest of these.

**Comment by flagersgit** [comment]
For interested parties, the device IDs were taken from:
https://github.com/linuxhw/DevicePopulation/blob/master/README.md

**Comment by flagersgit** [comment]
Revision has been pushed, waiting for review.

**Review by khronokernel — APPROVED** [review]

**Comment by khronokernel** [comment]
Thanks for the PR!

**Comment by Ausdauersportler** [comment]
Fermi GPU had never macOS support, no OpenGL and no metal acceleration to my knowledge.

**Pull request merged**
